In [1]:
import numpy as np 

x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
ravelled_array = x.ravel() # 다차원 배열을 1차원 배열로 변환
ravelled_array[2] = 1000000 # ravel은 원본이 변경됨
print(ravelled_array)
print(x)

[      0       1 1000000       3       4       5       6       7       8]
[[      0       1 1000000]
 [      3       4       5]
 [      6       7       8]]


In [5]:
flattened_array = x.flatten() # flatten은 원본이 변경되지 않음
flattened_array[2] = 10000000
print(flattened_array)
print(x)

[       0        1 10000000        3        4        5        6        7
        8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
y = np.arange(9)
y.shape = [3, 3]
print(y)
print(y.transpose())
print(y.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [11]:
print(np.resize(y, (6, 6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [14]:
print(np.zeros((6,), dtype = int))

[0 0 0 0 0 0]


In [15]:
print(np.zeros((2, 3), dtype = int))

[[0 0 0]
 [0 0 0]]


In [17]:
print(np.ones((6,), dtype = int))

[1 1 1 1 1 1]


In [21]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
np.random.rand(4, 4)

array([[0.49803032, 0.96883881, 0.14059104, 0.64620093],
       [0.3539997 , 0.43506179, 0.85967077, 0.20847625],
       [0.5191116 , 0.10861803, 0.29802979, 0.44123139],
       [0.3461264 , 0.85966405, 0.37474038, 0.85937389]])