In [2]:
import numpy as np 

x = np.arange(18).reshape(3, 2, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [8]:
x[1, 1, 1]

10

In [10]:
x[1, 0:2, 1]

array([ 7, 10])

In [11]:
x[1, 0:2, 0:3]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
x[1, ...]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
x[:, 0, 0]

array([ 0,  6, 12])

In [15]:
x[1, :2, :3 :2]

array([[ 6,  8],
       [ 9, 11]])

In [16]:
comparison_operation = x > 5
print(comparison_operation)

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]


In [17]:
x[comparison_operation]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [18]:
x[x > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [19]:
x.max()

17

In [20]:
x.min()

0