In [20]:
import numpy as np 

x = np.arange(0, 3)
y = np.arange(3, 6)
z = np.arange(6, 9)

multi_array = np.array([x, y, z], dtype= np.uint8)
print(multi_array)
print(multi_array.shape)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [21]:
multi_array[1, 2]
multi_array.dtype

dtype('uint8')

In [17]:
w = np.linspace(1, 10, 100, False)
print(w)

[1.   1.09 1.18 1.27 1.36 1.45 1.54 1.63 1.72 1.81 1.9  1.99 2.08 2.17
 2.26 2.35 2.44 2.53 2.62 2.71 2.8  2.89 2.98 3.07 3.16 3.25 3.34 3.43
 3.52 3.61 3.7  3.79 3.88 3.97 4.06 4.15 4.24 4.33 4.42 4.51 4.6  4.69
 4.78 4.87 4.96 5.05 5.14 5.23 5.32 5.41 5.5  5.59 5.68 5.77 5.86 5.95
 6.04 6.13 6.22 6.31 6.4  6.49 6.58 6.67 6.76 6.85 6.94 7.03 7.12 7.21
 7.3  7.39 7.48 7.57 7.66 7.75 7.84 7.93 8.02 8.11 8.2  8.29 8.38 8.47
 8.56 8.65 8.74 8.83 8.92 9.01 9.1  9.19 9.28 9.37 9.46 9.55 9.64 9.73
 9.82 9.91]


In [18]:
b = np.arange(1, 30, 3)
b

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [19]:
c = np.linspace(1, 30, 3)
c

array([ 1. , 15.5, 30. ])