In [5]:
import numpy as np 

y = np.arange(9).reshape(3, 3) # (3, -1)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
x = np.arange(18).reshape(2, 3, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [7]:
x = np.arange(18).reshape(3, 3, 2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
