In [24]:
import numpy as np 

x = np.arange(4).reshape(2, 2)
print(x)
print(x.shape)

[[0 1]
 [2 3]]
(2, 2)


In [25]:
y = np.arange(4, 8).reshape(2, 2)
print(y)

[[4 5]
 [6 7]]


In [26]:
z = np.hstack((x, y)) # 수평 방향으로 배열 연결 (같은 행을 가져야 함)
print(z)
print(z.shape)

[[0 1 4 5]
 [2 3 6 7]]
(2, 4)


In [27]:
h = np.vstack((x, y)) # 수직 방향으로 배열 연결 (같은 열을 가져야 함)
print(h)
print(h.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


In [28]:
w = np.concatenate((x, y), axis = 1)
print(w)

[[0 1 4 5]
 [2 3 6 7]]


In [29]:
z = np.hstack((x, y))

In [31]:
y = x * 2 
print(y)

[[0 2]
 [4 6]]


In [32]:
depth_stack = np.dstack((x, y)) #차원 추가 (같은 차원이여야 함)
print(depth_stack)

[[[0 0]
  [1 2]]

 [[2 4]
  [3 6]]]


In [33]:
print(depth_stack.shape)

(2, 2, 2)


In [34]:
print(np.column_stack((x, y))) # 열 방향으로 쌓음

[[0 1 0 2]
 [2 3 4 6]]


In [35]:
print(np.column_stack((x, y)) == np.hstack((x, y))) 

[[ True  True  True  True]
 [ True  True  True  True]]


In [36]:
print(np.hstack((x, y)))

[[0 1 0 2]
 [2 3 4 6]]


In [37]:
print(np.row_stack((x, y)))

[[0 1]
 [2 3]
 [0 2]
 [4 6]]


In [38]:
print(np.row_stack((x, y)) == np.vstack((x, y)))

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
